// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubpcqbehdsvxwkkdxbhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVicGNxYmVoZHN2eHdra2R4YmhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1NzQyNDksImV4cCI6MjA1MDE1MDI0OX0.wbZr7tE4vmN4EQDIeONUJGQVFK664ETx0SeD_yhWbqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);